name: multiple jobs - one after another
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo 'hello'
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: print hi
        run: echo 'hi'
