#container will run inside ubuntu vm, steps inside ubuntu vm


name: service containers
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11.4
        ports: 
          - 3306:3306
        env:
          MARIADB_USER: root
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: testdb
    steps:
      - name: print
        run: echo 'hello'

