name: schedule workflow
on:
  schedule:
    - cron: '13 19 * * *' 
  workflow_dispatch:
jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: print time
        run: echo 'Current time $date'
