name: multiple jobs
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print hello
        run: echo 'hello'
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print bye
        run: echo 'bye'
    
