name: multiple jobs - parallel
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: sleep for 15 sec
        run: sleep 15
      - name: print hello
        run: echo 'hello'
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print bye
        run: echo 'bye'
    
